build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy matplotlib pytest networkx scikit-learn pytest-cov"
  - activate test-environment
  - pip install coverage
  - pip install nibabel
  - pip install --use-wheel --no-index --find-links=XXX python-igraph
  # - pip install python-igraph  # doesn't work on windows
  - python setup.py install

test_script:
  - mkdir for_test
  - cd for_test
  - py.test --pyargs nigraph --cov-report term-missing --cov=nigraph
